const adminControler=require('../controller/adminControler')
var express = require("express")
var router = express.Router()
router.get("/", adminControler.adminLoginPage)
router.get("/loadDashboard", adminControler.loadDashBoardAgain)
router.post("/dashboard", adminControler.loadDashBoard)
router.get("/userList", adminControler.userList)
router.get("/block", adminControler.block)
router.get("/unblock", adminControler.unblock)
router.get("/acceptCancelation", adminControler.acceptCancel)
router.get("/rejectCancelation", adminControler.rejectCancel)
router.get("/acceptReturn", adminControler.acceptReturn)
router.get("/loadNotification", adminControler.notificationLoad)
router.post("/fetchData/:time", adminControler.fetchDataGraph)
router.post("/search", adminControler.search)
router.post("/orderSearch", adminControler.orderSearch)
router.get("/logout", adminControler.adminLogout)
module.exports=router
