const customerControler=require('../controller/customerControler')
var express = require("express")
var router = express.Router()
router.get("/", customerControler.loginPage)
router.post("/signup", customerControler.insertingUser)
router.post("/verify", customerControler.insertUser)
router.get("/sendingOTP", customerControler.sendingOTP)
router.get("/sendingOtpAgain", customerControler.sendingOtpAgain)
router.post("/login", customerControler.userLogin)
router.get("/forgotPassword", customerControler.forgotPasswordLoad)
router.post("/forgotPassword", customerControler.forgotPassword)
router.post("/verifyUser", customerControler.verifyUserResetPassword)
router.post("/resetPassword", customerControler.resetPassword)
router.get("/resetPassword", customerControler.resetPasswordLoad)
router.get("/continueShopping", customerControler.loginPage)
router.post("/search", customerControler.search)
router.get("/success", customerControler.googleAuthSuccess)
router.get("/auth/google", customerControler.googleAuth)
router.get("/google/callback", customerControler.googleCallback)
router.get("/logout", customerControler.userLogout)

module.exports=router
